[darwin.common]
taps = ["homebrew/autoupdate"]

[darwin.personal]
casks = [
  "font-fira-code-nerd-font",
  "font-iosevka-nerd-font",
  "font-caskaydia-cove-nerd-font",

  "keepassxc",
  "cursor",
  "google-drive",
  "iina",
  "keka",
  "localsend",
  "pearcleaner",
  "rectangle",
  "rustdesk",
  "onyx",
  "signal",
  "telegram-desktop",
  "tor-browser",
  "transmission",
  "veracrypt",
  "visual-studio-code",
  "xnviewmp",
  "zoom",
  "stats",
  "macfuse",

  "superhuman",
  "figma",
  "loom",
  "flux",
  "arc",
  "calibre",
  "wezterm",
  "discord",
  "raycast",
  "obsidian",
  "tableplus",
  "local",
  "termius",
]
mas = [
  { name = "Keynote", id = 409183694 },
  { name = "Numbers", id = 409203825 },
  { name = "Pages", id = 409201541 },
  { name = "Slack", id = 803453959 },
  { name = "Tailscale", id = 1475387142 },
  { name = "iStat Menus", id = 1319778037 },
  { name = "WhatsApp", id = 310633997 },
  { name = "Notability", id = 360593530 },
  { name = "Dashlane", id = 517914548 },
]

[darwin.work]
